# Generated by Django 5.1.4 on 2025-02-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
